### ISSUE TITLE
Use fsPath instead of path when retrieving object paths

### ISSUE THREAD

**Issue by JoBrad** [brpaz/vscode-file-templates-ext#2]
In templateFromFileCommand.ts and fileFromTemplateCommand.ts, the path is being set using path. This only works on Linux. It should use fsPath instead, since this value changes based on the OS being used. 

For additional reference, check out line 104 in the [vscode uri module](https://github.com/Microsoft/vscode/blob/2f76c44632b0d47ba97f66fbc158c763628e30b3/extensions/json/server/src/utils/uri.ts). I have cloned this repo, and can add the updated files, if you like.

**Line 23 in templateFromFileCommand.ts**
```js
    let filePath = args ? args.fsPath : vscode.window.activeTextEditor.document.fileName;
```

**Line 23 in fileFromTemplateCommand.ts**
```js
    let targetFolder = args ? args.fsPath : vscode.workspace.rootPath;
```

Edit: added code and some formatting.

**Comment by brpaz** [comment]
Fixed by PR #5
