### ISSUE TITLE
Create template from file fails

### ISSUE THREAD

**Issue by JoBrad** [brpaz/vscode-file-templates-ext#4]
Line 34 of templateFromFileCommand.ts references a variable (filename) that hasn't been set. This causes the fs.writeFile command to fail, because it's trying to write file contents into a directory. It should be updated to reference the basename:
```js
        let templateFile = path.join(templatesManager.getTemplatesDir(), path.basename(filePath));
```

**Comment by brpaz** [comment]
Fixed by PR #5
